config/routes.rb
Highlights::Application.routes.draw do
	get 'signin', to: 'sessions#new', as: 'signin'
	post 'signin', to: 'sessions#create', as: 'sessions'
	get 'signout', to: 'sessions#destroy', as: 'signout'

	get 'books', to: 'books#index', as: 'books'
	get 'books/:asin', to: 'books#show', as: 'book'
	get 'books/test', to: 'books#test'

   root :to => 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def signed_in?
  	if session[:email] && session[:password]
  		true
  	else
  		false
  	end
  end
  helper_method :signed_in?

end

app/controllers/books_controller.rb
require 'actionpack/action_caching'

class BooksController < ApplicationController
	before_filter :authenticate_user

	caches_action :index, expires_in: 30.minutes
	caches_action :show, expires_in: 30.minutes

	def index
		@agent = Mechanize.new
	  @agent.user_agent_alias = 'Mac Safari'
	  @agent.get("https://kindle.amazon.com/")
	  if @agent.page.link_with(text: 'Guest')
		  @agent.get("https://kindle.amazon.com/login")
		  form = @agent.page.form_with(id: "ap_signin_form")
		  form.email = session[:email]
		  form.password = session[:password]
		  form.submit
		end
		if @agent.page.link_with(text: 'Your Books')
		  @agent.page.link_with(text: "Your Books").click
		  @agent.page.link_with(text: "Read").click

			@results = @agent.page.search(".titleAndAuthor a")

			@books = []
			@results.each do |result|
				book = Hash.new
				book[:title] = result.content
				book[:asin] = result["href"].split("/").last
				@books << book
			end

			while @agent.page.link_with(text: "Next >")
				@agent.page.link_with(text: "Next >").click
				@results = @agent.page.search(".titleAndAuthor a")
				@results.each do |result|
					book = Hash.new
					book[:title] = result.content
					book[:asin] = result["href"].split("/").last
					@books << book
				end
			end
		else
			redirect_to signin_path, alert: 'Sorry, we could not log you into your Kindle account.'
		end

	end

	def show
		agent = Mechanize.new
	  agent.user_agent_alias = 'Mac Safari'
	  agent.get("https://kindle.amazon.com/your_highlights_and_notes/#{params[:asin]}")
	  form = agent.page.forms.first
	  form.email = session[:email]
	  form.password = session[:password]
	  form.submit

	  @title = agent.page.search(".title")
	  @author = agent.page.search(".author")
	  @highlights = agent.page.search(".highlight")
	end

	def test
	end

	private

		def authenticate_user
			redirect_to signin_path unless signed_in?
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	  session[:email] = params[:email]
	  session[:password] = params[:password]
	  redirect_to books_path
  end

  def destroy
  	session[:email] = nil
  	session[:password] = nil
  	redirect_to root_url, notice: "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_header.html.erb
<header>
	<div class="container clearfix">
		<%= link_to 'Books', books_path, class: 'home_link' %>
		<%= link_to 'Sign out', signout_path, class: 'signout_link' if signed_in? %>
	</div>
</header>

app/views/books/index.html.erb
<%= render 'header' %>

<div class="container">
	<h1>Your Books</h1>

	<ul class="books">
		<% @books.each do |book| %>
			<li class="book"><%= link_to book[:title], book_path(book[:asin]) %></li>
		<% end %>
	</ul>
</div>

app/views/books/show.html.erb
<%= render 'header' %>

<div class="container">
	<h1><%= @title.text %></h1>
	<h3><%= @author.text %></h3>
	<div class="highlights">
		<% @highlights.each do |highlight| %>
			<p><%= highlight.text %></p>
		<% end %>
	</div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
	<div class="flash <%= key %>"><%= value %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <title>Highlights</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!--[if IE]>
    <script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

	<%= yield %>

</body>
</html>